// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW-cAu3EdVkTFz4z_2tYFFjNa_wTZQbqk',
    appId: '1:622026417586:android:95993880c16ee709ddb0ab',
    messagingSenderId: '622026417586',
    projectId: 'flutter-mynotes-pjet',
    storageBucket: 'flutter-mynotes-pjet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgUgeoJ_h1NyT2-B_cM_Ffh9WSVNGC3l8',
    appId: '1:622026417586:ios:c44167f57f7e8196ddb0ab',
    messagingSenderId: '622026417586',
    projectId: 'flutter-mynotes-pjet',
    storageBucket: 'flutter-mynotes-pjet.appspot.com',
    iosClientId: '622026417586-tpggqri8r3208mrqprmo707uu5h6tgie.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttercourse',
  );
}
